Minor amendments to docs
spsrc/droplets pull request #7
Opened 2020-02-10 13:21 UTC by sebastian-luna-valero

Add OSX steps.

2020-02-10 14:34 UTC, jmoldon commented
I think it is easier for Mac users if they have all the commands they need together (without having to understand what "as above" means).

So I would duplicate the information in this case.

[Can I modify this pull request with that change?]

2020-02-10 17:59 UTC, jmoldon requested changes
There is a typo in line 30

2020-02-10 17:59 UTC, jmoldon commented on docs/quickstart.md
> +conda create env -f environment.yml
conda env create -f environment.yml

2020-02-11 08:54 UTC, sebastian-luna-valero commented
I have updated the docs as requested. Please feel free to add your suggestions.

2020-02-11 09:00 UTC, merged